### ISSUE TITLE
2.1.66 compatability

### ISSUE THREAD

**Issue by kleemat** [mathewthe2/AnkiDojo#10]
Hi! Just a heads up I got errors installing on the latest 2.1 release, 2.1.66. However, it works fine if I go back a few versions to 2.1.61.

Not sure if you want to try and fix this or if you're aiming to update to 23.*, but I figured I'd flag it in case anyone else has a similar problem.

**Comment by mathewthe2** [comment]
Thanks for the heads up. 

I'll see if I can release a patch for 23.10.1

I'll add the releases to this Github page with their respective supported versions. I'm only one person working on this, so let me know if you have any issues with subsequent versions.

There is a `Copy Debug` button on the error dialog when you launch Anki. That would help if you could paste it here.

```
When loading AnkiDojo:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "/Users/mathew/Library/Application Support/Anki2/addons21/AnkiDojo/__init__.py", line 22, in <module>
    server = create_server()
  File "/Users/mathew/Library/Application Support/Anki2/addons21/AnkiDojo/__init__.py", line 20, in create_server
    return Server('0.0.0.0', 5008, dev_mode=config['dev_mode'])
  File "/Users/mathew/Library/Application Support/Anki2/addons21/AnkiDojo/server/run_server.py", line 15, in __init__
    self.app = create_flask_app(dev_mode=dev_mode)
  File "/Users/mathew/Library/Application Support/Anki2/addons21/AnkiDojo/server/flask_app.py", line 53, in create_flask_app
    from . import blueprint
  File "/Users/mathew/Library/Application Support/Anki2/addons21/AnkiDojo/server/blueprint.py", line 5, in <module>
    from .japanese import Japanese
  File "/Users/mathew/Library/Application Support/Anki2/addons21/AnkiDojo/server/japanese/__init__.py", line 7, in <module>
    from .audio_handler import AudioHandler
  File "/Users/mathew/Library/Application Support/Anki2/addons21/AnkiDojo/server/japanese/audio_handler.py", line 216, in <module>
    class AudioHandler():
  File "/Users/mathew/Library/Application Support/Anki2/addons21/AnkiDojo/server/japanese/audio_handler.py", line 217, in AudioHandler
    forvo = Forvo(config=_forvo_config)
  File "/Users/mathew/Library/Application Support/Anki2/addons21/AnkiDojo/server/japanese/audio_handler.py", line 68, in __init__
    self._set_session()
  File "/Users/mathew/Library/Application Support/Anki2/addons21/AnkiDojo/server/japanese/audio_handler.py", line 75, in _set_session
    retry_strategy = Retry(
TypeError: __init__() got an unexpected keyword argument 'method_whitelist'
```

**Comment by mathewthe2** [comment]
Update: I patched it and uploaded the newest version for Anki with version 23.10.1+
